# ngspice
tclsh ./subcircuit.tcl
tclsh ./netlist_manipulations.tcl
cd ngspice/dc
tclsh ./resistor_divider.tcl
tclsh ./diode_iv.tcl
cd ../ac
tclsh ./diode_cv.tcl
cd ../transient
tclsh ./switch_oscillator.tcl
tclsh ./fourbitadder.tcl
cd ../advanced
tclsh ./monte_carlo.tcl
tclsh ./diode_extract.tcl
tclsh ./verilog_a_magnetic.tcl
# xyce
cd ../../xyce/dc
tclsh ./resistor_divider.tcl
tclsh ./diode_iv.tcl
cd ../ac
tclsh ./diode_cv.tcl
cd ../transient
tclsh ./switch_oscillator.tcl
tclsh ./fourbitadder.tcl
cd ../advanced
tclsh ./monte_carlo.tcl
# ltspice
cd ../../ltspice/dc
tclsh ./resistor_divider.tcl
tclsh ./diode_iv.tcl
cd ../ac
tclsh ./diode_cv.tcl
cd ../transient
tclsh ./switch_oscillator.tcl
tclsh ./fourbitadder.tcl
