# ngspice
tclsh90 ./subcircuit.tcl
tclsh90 ./netlist_manipulations.tcl
cd ngspice/dc
tclsh90 ./resistor_divider.tcl
tclsh90 ./diode_iv.tcl
cd ../ac
tclsh90 ./diode_cv.tcl
cd ../transient
tclsh90 ./switch_oscillator.tcl
tclsh90 ./fourbitadder.tcl
cd ../advanced
tclsh90 ./monte_carlo.tcl
tclsh90 ./diode_extract.tcl
tclsh90 ./verilog_a_magnetic.tcl
tclsh90 ./inverter_optimization.tcl
# xyce
cd ../../xyce/dc
tclsh90 ./resistor_divider.tcl
tclsh90 ./diode_iv.tcl
cd ../ac
tclsh90 ./diode_cv.tcl
cd ../transient
tclsh90 ./switch_oscillator.tcl
tclsh90 ./fourbitadder.tcl
cd ../advanced
tclsh90 ./monte_carlo.tcl
# ltspice
cd ../../ltspice/dc
tclsh90 ./resistor_divider.tcl
tclsh90 ./diode_iv.tcl
cd ../ac
tclsh90 ./diode_cv.tcl
cd ../transient
tclsh90 ./switch_oscillator.tcl
tclsh90 ./fourbitadder.tcl
