tclsh ./subcircuit.tcl
tclsh ./netlist_manipulations.tcl
cd ngspice/dc
tclsh ./resistor_divider.tcl
tclsh ./diode_iv.tcl
cd ../ac
tclsh ./diode_cv.tcl
cd ../transient
tclsh ./switch_oscillator.tcl
tclsh ./fourbitadder.tcl
cd ../advanced
tclsh ./monte_carlo.tcl
cd ../../xyce/dc
tclsh ./resistor_divider.tcl
tclsh ./diode_iv.tcl
cd ../ac
tclsh ./diode_cv.tcl
cd ../transient
tclsh ./switch_oscillator.tcl
tclsh ./fourbitadder.tcl
cd ../advanced
tclsh ./monte_carlo.tcl
